'use client'

import { useState, useRef } from 'react'
import Link from 'next/link'
import { Loader2, AlertTriangle, Sparkles, MapPin, Clock, Users, RefreshCw, ArrowLeft } from 'lucide-react'

const generateFallbackItinerary = (hours: string, companion: string, location: string) => {
  const spots: Record<string, Array<{ name: string, time: string, cost: string, activity: string }>> = {
    '2': [
      { name: 'Vasai Fort', time: '1 hour', cost: '₹0 (Free entry)', activity: 'Explore Portuguese ruins' },
      { name: 'Local Cafe', time: '1 hour', cost: '₹300-500', activity: 'Coffee and snacks' }
    ],
    '4': [
      { name: 'Vasai Fort', time: '1.5 hours', cost: '₹0 (Free entry)', activity: 'Historical exploration' },
      { name: 'Arnala Beach', time: '2 hours', cost: '₹50 (Transport)', activity: 'Beach time and seafood' },
      { name: 'Local Market', time: '30 mins', cost: '₹200', activity: 'Shopping and street food' }
    ],
    '6': [
      { name: 'Tungareshwar Temple', time: '2 hours', cost: '₹0 + ₹100 transport', activity: 'Nature trek and temple visit' },
      { name: 'Vasai Fort', time: '1.5 hours', cost: '₹0', activity: 'Sunset photography' },
      { name: 'Seafood Restaurant', time: '1.5 hours', cost: '₹600-800', activity: 'Authentic Vasai cuisine' },
      { name: 'Market Street', time: '1 hour', cost: '₹300', activity: 'Local shopping' }
    ]
  }

  const selectedSpots = spots[hours] || spots['4']
  let output = `🗺️ ${hours}-Hour Itinerary\n👥 ${companion}\n📍 Starting: ${location}\n\n`

  selectedSpots.forEach((spot, i) => {
    output += `${i + 1}. ${spot.name} (${spot.time})\n   🎯 ${spot.activity}\n   💰 ${spot.cost}\n\n`
  })

  return output + `💡 Tips:\n- Book transport in advance\n- Carry water and sunscreen\n- Try local seafood specialties\n- Best time: Early morning or evening`
}

export default function AIPlannerPage() {
  const [timeAvailable, setTimeAvailable] = useState('2')
  const [companionType, setCompanionType] = useState('Friends')
  const [startLocation, setStartLocation] = useState('')
  const [loading, setLoading] = useState(false)
  const [modelLoading, setModelLoading] = useState(false)
  const [itinerary, setItinerary] = useState('')
  const [error, setError] = useState('')

  // Cache the model pipeline to prevent reloading
  const pipelineRef = useRef<any>(null)

  const loadModel = async () => {
    // If model is already loaded, return existing pipeline
    if (pipelineRef.current) return

    try {
      setModelLoading(true)

      // Dynamic import inside function to avoid server-side issues
      const { pipeline } = await import('@xenova/transformers')

      // Load the Flan-T5-Small model (approx 80MB)
      // This happens entirely in the browser
      pipelineRef.current = await pipeline('text2text-generation', 'Xenova/flan-t5-small')

      setModelLoading(false)
    } catch (err) {
      console.error('Model load error:', err)
      setError('Failed to download AI model. Please check your internet connection.')
      setModelLoading(false)
      throw err // Re-throw to stop generation flow
    }
  }

  const generateItinerary = async () => {
    // 1. Validation
    if (!startLocation.trim()) {
      setError('Please enter a starting location.')
      return
    }

    setLoading(true)
    setError('')

    try {
      // 2. Ensure model is loaded (only downloads on first run)
      await loadModel()

      // 3. Build Prompt
      const prompt = `Plan a ${timeAvailable} hour trip in Vasai-Virar starting from ${startLocation}. Companion: ${companionType}. List exactly 2-3 places with format:
1. Place name - Activity (timing, travel time, cost in ₹)
2. Place name - Activity (timing, travel time, cost in ₹)
Include: Tungareshwar Temple, Vasai Fort, Arnala Beach, Global Vipassana Pagoda, or local cafes.`

      // 4. Generate Content
      // max_length: 512 tokens for detailed output
      const result = await pipelineRef.current(prompt, {
        max_length: 512,
        temperature: 0.7,
        top_p: 0.9,
      })

      // 5. Extract and Format Result
      if (result && result[0] && result[0].generated_text) {
        const generatedText = result[0].generated_text

        // Check if output is too short/vague
        if (generatedText.length < 100) {
            console.log('AI output too short, using fallback')
            setItinerary(generateFallbackItinerary(timeAvailable, companionType, startLocation))
        } else {
            // Add header and footer details to the raw output
            const formattedItinerary = `Itinerary: ${timeAvailable} Hours | With: ${companionType} | From: ${startLocation}\n\n${generatedText}\n\nTips: Wear comfortable shoes and carry water! Check local train timings if traveling between Vasai and Virar.`
            setItinerary(formattedItinerary)
        }
      } else {
        throw new Error('No output generated by the model.')
      }

    } catch (err) {
      console.error('Generation failed:', err)
      // Fallback on error as well
      console.log('Generation error, using fallback')
      setItinerary(generateFallbackItinerary(timeAvailable, companionType, startLocation))
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen w-full bg-gradient-to-br from-gray-900 via-purple-900 to-black p-4 md:p-8 flex flex-col items-center overflow-y-auto">

      <div className="w-full max-w-2xl space-y-6 mt-4 mb-12">

        {/* Header Section */}
        <div className="text-center space-y-2">
          <h1 className="text-4xl md:text-5xl font-extrabold bg-gradient-to-r from-cyan-400 to-pink-500 bg-clip-text text-transparent drop-shadow-lg font-heading">
            🤖 AI Day Planner
          </h1>
          <p className="text-gray-300 text-lg">
            Plan your perfect day in Vasai-Virar
          </p>
          {pipelineRef.current && !modelLoading && (
             <div className="inline-flex items-center gap-1 px-3 py-1 rounded-full bg-green-500/20 text-green-400 text-sm font-medium border border-green-500/30 animate-in fade-in duration-500">
               <span>✅</span> AI Model Ready
             </div>
          )}
        </div>

        {/* Model Loading Alert */}
        {modelLoading && (
          <div className="w-full p-4 rounded-lg border border-blue-500/50 bg-blue-900/20 backdrop-blur-sm flex items-start gap-3 animate-pulse">
            <Loader2 className="w-5 h-5 text-blue-400 animate-spin mt-1 shrink-0" />
            <div>
              <h3 className="text-blue-200 font-semibold">Downloading AI Model...</h3>
              <p className="text-blue-300/80 text-sm">~80MB, one-time download. This may take 1-2 minutes.</p>
            </div>
          </div>
        )}

        {/* Error Alert */}
        {error && (
          <div className="w-full p-4 rounded-lg border border-red-500/50 bg-red-900/20 backdrop-blur-sm flex items-center justify-between gap-3 animate-in slide-in-from-top-2">
             <div className="flex items-center gap-3">
                <AlertTriangle className="w-5 h-5 text-red-400 shrink-0" />
                <p className="text-red-200">{error}</p>
             </div>
             <button
               onClick={generateItinerary}
               className="text-xs bg-red-500/20 hover:bg-red-500/30 text-red-300 px-3 py-1 rounded border border-red-500/30 transition-colors"
             >
               Try Again
             </button>
          </div>
        )}

        {/* Input Form Card */}
        <div className="w-full bg-black/40 backdrop-blur-md border border-cyan-500/50 rounded-xl p-6 md:p-8 shadow-[0_0_20px_rgba(6,182,212,0.15)] relative overflow-hidden group">
           {/* Cyberpunk accent lines */}
           <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-cyan-500 to-pink-500 opacity-50" />

           <div className="space-y-6">

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                 {/* Time Available */}
                 <div className="space-y-2">
                    <label className="text-cyan-400 text-sm font-bold uppercase tracking-wider">
                       Time Available (Hours)
                    </label>
                    <div className="relative">
                       <Clock className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 w-4 h-4" />
                       <input
                         type="number"
                         min="1"
                         max="12"
                         value={timeAvailable}
                         onChange={(e) => setTimeAvailable(e.target.value)}
                         className="w-full bg-gray-900/80 border border-gray-700 focus:border-cyan-500 rounded-lg py-3 pl-10 pr-4 text-white outline-none transition-colors"
                       />
                    </div>
                 </div>

                 {/* Companion Type */}
                 <div className="space-y-2">
                    <label className="text-cyan-400 text-sm font-bold uppercase tracking-wider">
                       Companion
                    </label>
                    <div className="relative">
                       <Users className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 w-4 h-4" />
                       <select
                         value={companionType}
                         onChange={(e) => setCompanionType(e.target.value)}
                         className="w-full bg-gray-900/80 border border-gray-700 focus:border-cyan-500 rounded-lg py-3 pl-10 pr-4 text-white outline-none transition-colors appearance-none"
                       >
                          <option value="Girlfriend/Partner">💑 Girlfriend/Partner</option>
                          <option value="Friends">👯 Friends</option>
                          <option value="Family">👨‍👩‍👧‍👦 Family</option>
                          <option value="Solo">👤 Solo</option>
                       </select>
                    </div>
                 </div>
              </div>

              {/* Start Location */}
              <div className="space-y-2">
                 <label className="text-cyan-400 text-sm font-bold uppercase tracking-wider">
                    Starting Location
                 </label>
                 <div className="relative">
                    <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 w-4 h-4" />
                    <input
                      type="text"
                      placeholder="e.g. Vasai Railway Station"
                      value={startLocation}
                      onChange={(e) => setStartLocation(e.target.value)}
                      className="w-full bg-gray-900/80 border border-gray-700 focus:border-cyan-500 rounded-lg py-3 pl-10 pr-4 text-white outline-none transition-colors placeholder:text-gray-600"
                    />
                 </div>
              </div>

              {/* Generate Button */}
              <button
                onClick={generateItinerary}
                disabled={loading || modelLoading || !startLocation}
                className={`w-full py-4 rounded-lg font-bold text-lg text-white shadow-lg transition-all duration-300 relative overflow-hidden
                  ${(loading || modelLoading || !startLocation)
                    ? 'bg-gray-800 cursor-not-allowed opacity-50'
                    : 'bg-gradient-to-r from-cyan-500 to-pink-500 hover:scale-[1.02] hover:shadow-cyan-500/25'
                  }`}
              >
                 <div className="flex items-center justify-center gap-2">
                    {loading || modelLoading ? (
                       <>
                          <Loader2 className="w-5 h-5 animate-spin" />
                          <span>{modelLoading ? 'Loading AI Model...' : 'Generating Itinerary...'}</span>
                       </>
                    ) : (
                       <>
                          <Sparkles className="w-5 h-5" />
                          <span>✨ Generate Itinerary</span>
                       </>
                    )}
                 </div>
              </button>

           </div>
        </div>

        {/* Results Section */}
        {itinerary && (
          <div className="w-full bg-black/40 backdrop-blur-md border border-pink-500/50 rounded-xl p-6 md:p-8 shadow-[0_0_20px_rgba(236,72,153,0.15)] animate-in fade-in slide-in-from-bottom-4 duration-700">
             <div className="flex items-center justify-between mb-6 border-b border-pink-500/20 pb-4">
                <h2 className="text-2xl font-bold text-pink-400 flex items-center gap-2 font-heading">
                   🎉 Your Itinerary
                </h2>
                <button
                   onClick={generateItinerary}
                   className="text-sm text-pink-300/70 hover:text-pink-300 flex items-center gap-1 transition-colors"
                >
                   <RefreshCw className="w-4 h-4" /> Regenerate
                </button>
             </div>

             <div className="prose prose-invert max-w-none">
                <div className="whitespace-pre-wrap text-gray-200 leading-relaxed font-light text-lg">
                   {itinerary}
                </div>
             </div>
          </div>
        )}

        {/* Back Link */}
        <div className="flex justify-center pt-4 pb-8">
           <Link href="/dashboard" className="text-cyan-400 hover:text-cyan-300 flex items-center gap-2 transition-colors font-medium">
              <ArrowLeft className="w-4 h-4" /> Back to Dashboard
           </Link>
        </div>

      </div>
    </div>
  )
}
